// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'server.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3868304714150152418),
    name: 'SemaphoreServer',
    lastPropertyId: const obx_int.IdUid(6, 2183294552473964639),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1776666396979582386),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1520022377381729051),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8817598683985249732),
        name: 'apiUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7690038087564407010),
        name: 'username',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1544831913107901190),
        name: 'token',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2183294552473964639),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'projects',
        srcEntity: 'SemaphoreProject',
        srcField: 'server',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5513399277581180072),
    name: 'SemaphoreProject',
    lastPropertyId: const obx_int.IdUid(9, 1648089115667526287),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8938446581606169630),
        name: 'serverId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 8202018018294231874),
        relationTarget: 'SemaphoreServer',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5003460447966498152),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5033952148264635469),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1538501707662306262),
        name: 'alert',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4444877333518017430),
        name: 'alertChat',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6106321196910289234),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5478272745477385043),
        name: 'maxParallelTasks',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1648089115667526287),
        name: 'projectId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 5513399277581180072),
    lastIndexId: const obx_int.IdUid(1, 8202018018294231874),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [1766001262715329367],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    SemaphoreServer: obx_int.EntityDefinition<SemaphoreServer>(
      model: _entities[0],
      toOneRelations: (SemaphoreServer object) => [],
      toManyRelations: (SemaphoreServer object) => {
        obx_int.RelInfo<SemaphoreProject>.toOneBacklink(
          1,
          object.id,
          (SemaphoreProject srcObject) => srcObject.server,
        ): object.projects,
      },
      getId: (SemaphoreServer object) => object.id,
      setId: (SemaphoreServer object, int id) {
        object.id = id;
      },
      objectToFB: (SemaphoreServer object, fb.Builder fbb) {
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final apiUrlOffset = object.apiUrl == null
            ? null
            : fbb.writeString(object.apiUrl!);
        final usernameOffset = object.username == null
            ? null
            : fbb.writeString(object.username!);
        final tokenOffset = object.token == null
            ? null
            : fbb.writeString(object.token!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, apiUrlOffset);
        fbb.addOffset(3, usernameOffset);
        fbb.addOffset(4, tokenOffset);
        fbb.addInt64(5, object.createdAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final createdAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final object = SemaphoreServer()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 6)
          ..apiUrl = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 8)
          ..username = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 10)
          ..token = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 12)
          ..createdAt = createdAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
        obx_int.InternalToManyAccess.setRelInfo<SemaphoreServer>(
          object.projects,
          store,
          obx_int.RelInfo<SemaphoreProject>.toOneBacklink(
            1,
            object.id,
            (SemaphoreProject srcObject) => srcObject.server,
          ),
        );
        return object;
      },
    ),
    SemaphoreProject: obx_int.EntityDefinition<SemaphoreProject>(
      model: _entities[1],
      toOneRelations: (SemaphoreProject object) => [object.server],
      toManyRelations: (SemaphoreProject object) => {},
      getId: (SemaphoreProject object) => object.id,
      setId: (SemaphoreProject object, int id) {
        object.id = id;
      },
      objectToFB: (SemaphoreProject object, fb.Builder fbb) {
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final alertChatOffset = object.alertChat == null
            ? null
            : fbb.writeString(object.alertChat!);
        fbb.startTable(10);
        fbb.addInt64(0, object.server.targetId);
        fbb.addInt64(1, object.id);
        fbb.addOffset(2, nameOffset);
        fbb.addBool(3, object.alert);
        fbb.addOffset(4, alertChatOffset);
        fbb.addInt64(6, object.createdAt?.millisecondsSinceEpoch);
        fbb.addInt64(7, object.maxParallelTasks);
        fbb.addInt64(8, object.projectId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final createdAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final object = SemaphoreProject()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 8)
          ..alert = const fb.BoolReader().vTableGetNullable(
            buffer,
            rootOffset,
            10,
          )
          ..alertChat = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 12)
          ..createdAt = createdAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createdAtValue)
          ..maxParallelTasks = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            18,
          )
          ..projectId = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            20,
          );
        object.server.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        object.server.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [SemaphoreServer] entity fields to define ObjectBox queries.
class SemaphoreServer_ {
  /// See [SemaphoreServer.id].
  static final id = obx.QueryIntegerProperty<SemaphoreServer>(
    _entities[0].properties[0],
  );

  /// See [SemaphoreServer.name].
  static final name = obx.QueryStringProperty<SemaphoreServer>(
    _entities[0].properties[1],
  );

  /// See [SemaphoreServer.apiUrl].
  static final apiUrl = obx.QueryStringProperty<SemaphoreServer>(
    _entities[0].properties[2],
  );

  /// See [SemaphoreServer.username].
  static final username = obx.QueryStringProperty<SemaphoreServer>(
    _entities[0].properties[3],
  );

  /// See [SemaphoreServer.token].
  static final token = obx.QueryStringProperty<SemaphoreServer>(
    _entities[0].properties[4],
  );

  /// See [SemaphoreServer.createdAt].
  static final createdAt = obx.QueryDateProperty<SemaphoreServer>(
    _entities[0].properties[5],
  );

  /// see [SemaphoreServer.projects]
  static final projects =
      obx.QueryBacklinkToMany<SemaphoreProject, SemaphoreServer>(
        SemaphoreProject_.server,
      );
}

/// [SemaphoreProject] entity fields to define ObjectBox queries.
class SemaphoreProject_ {
  /// See [SemaphoreProject.server].
  static final server =
      obx.QueryRelationToOne<SemaphoreProject, SemaphoreServer>(
        _entities[1].properties[0],
      );

  /// See [SemaphoreProject.id].
  static final id = obx.QueryIntegerProperty<SemaphoreProject>(
    _entities[1].properties[1],
  );

  /// See [SemaphoreProject.name].
  static final name = obx.QueryStringProperty<SemaphoreProject>(
    _entities[1].properties[2],
  );

  /// See [SemaphoreProject.alert].
  static final alert = obx.QueryBooleanProperty<SemaphoreProject>(
    _entities[1].properties[3],
  );

  /// See [SemaphoreProject.alertChat].
  static final alertChat = obx.QueryStringProperty<SemaphoreProject>(
    _entities[1].properties[4],
  );

  /// See [SemaphoreProject.createdAt].
  static final createdAt = obx.QueryDateProperty<SemaphoreProject>(
    _entities[1].properties[5],
  );

  /// See [SemaphoreProject.maxParallelTasks].
  static final maxParallelTasks = obx.QueryIntegerProperty<SemaphoreProject>(
    _entities[1].properties[6],
  );

  /// See [SemaphoreProject.projectId].
  static final projectId = obx.QueryIntegerProperty<SemaphoreProject>(
    _entities[1].properties[7],
  );
}
