name: app_server
description: Server widgets for Semaphore client
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.10.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Workspace dependencies
  flutter_bloc: ^9.0.0
  settings_ui: any
  go_router: any
  app_utils: any
  server_bloc: any
  app_database: any
  app_feedback: any
  app_locale: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true